#!/usr/bin/env bash
# Vendor the exact browser dependencies of the 3D view from the npm registry, so the page
# does not depend on a CDN at runtime. Re-run after changing a version below.
set -euo pipefail

THREE=0.170.0
LILGUI=0.20.0
root=$(cd "$(dirname "$0")/.." && pwd)
dest="$root/src/flymsg/viz_static/vendor"
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

cd "$work"
npm pack --silent "three@$THREE" "lil-gui@$LILGUI" >/dev/null
mkdir three lil-gui
tar -xzf "three-$THREE.tgz" -C three --strip-components=1
tar -xzf "lil-gui-$LILGUI.tgz" -C lil-gui --strip-components=1

rm -rf "$dest"
jsm=examples/jsm
files=(
	build/three.module.min.js
	LICENSE
	"$jsm/controls/OrbitControls.js"
	"$jsm/loaders/DRACOLoader.js"
	"$jsm/libs/draco/draco_wasm_wrapper.js"
	"$jsm/libs/draco/draco_decoder.wasm"
	"$jsm/postprocessing/EffectComposer.js"
	"$jsm/postprocessing/MaskPass.js"
	"$jsm/postprocessing/OutputPass.js"
	"$jsm/postprocessing/Pass.js"
	"$jsm/postprocessing/RenderPass.js"
	"$jsm/postprocessing/ShaderPass.js"
	"$jsm/postprocessing/UnrealBloomPass.js"
	"$jsm/shaders/CopyShader.js"
	"$jsm/shaders/LuminosityHighPassShader.js"
	"$jsm/shaders/OutputShader.js"
)
for f in "${files[@]}"; do
	install -D -m 644 "three/$f" "$dest/three/$f"
done
install -D -m 644 lil-gui/dist/lil-gui.esm.min.js "$dest/lil-gui/lil-gui.esm.min.js"
install -D -m 644 lil-gui/LICENSE.md "$dest/lil-gui/LICENSE.md"

{
	echo "# Vendored browser dependencies"
	echo
	echo "Generated by \`scripts/vendor-js.sh\` from the npm registry; do not edit by hand."
	echo
	echo "| package | version | tarball sha256 |"
	echo "|---|---|---|"
	echo "| three | $THREE | $(sha256sum "three-$THREE.tgz" | cut -d' ' -f1) |"
	echo "| lil-gui | $LILGUI | $(sha256sum "lil-gui-$LILGUI.tgz" | cut -d' ' -f1) |"
} >"$dest/SOURCES.md"
echo "vendored three@$THREE and lil-gui@$LILGUI into $dest"
